# Generated by Django 4.0.1 on 2022-01-25 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOfBirds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Birds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название птицы')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('photo', models.ImageField(default='', upload_to='photos', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Описание')),
                ('audio', models.FileField(default='', upload_to='audio', verbose_name='Аудио')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.categoryofbirds', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Птицы',
                'verbose_name_plural': 'Птицы',
                'ordering': ['name'],
            },
        ),
    ]
